#!/bin/bash
# Write a script to print certain contains of a file:  a number of lines, 
# given as second parameter (7), from a line given as first parameter (5). 
# For instance,  if we called this script as frag and run as
# $ ./frag 5 7 myFile 
# Then frag prints the lines  5, 6, 7, 8, 9, 10 and 11 of the file myFile
# Clue: Use tail, head and wc commands. 
# Do not use pipe, just redirection to files
# Ensure the file has enough lines

tail -n +$1 < $3 > supportFile
echo `head -n$2 < supportFile`