#!/bin/bash

v1=2
v2=2
if [ $v1 = $v2 ] 
then 
    echo "Son iguales" 
else 
    echo "No son iguales" 
fi#!/bin/bash

if [ $1 = $2 ] 
then 
    echo "Son iguales" 
else 
    echo "No son iguales" 
fi#!/bin/bash

if [ $# -ne 2 ]
then
    echo `basename $0`: I need two parameters
fi

if [ $1 = $2 ] 
then 
    echo "Son iguales" 
else 
    echo "No son iguales" 
fi#!/bin/bash

if [ $# -ne 2 ]
then
    echo `basename $0`: I need two parameters 1>&2
fi

if [ $1 = $2 ] 
then 
    echo "Son iguales" 
else 
    echo "No son iguales" 
fi#!/bin/bash

pack(){
    p=$1
    shift
    cat $* > $p
}
pack uwu uwu1 uwu2#!/bin/bash

pack(){
    p=$1
    shift
    cat $* > $p
}
pack uwu *#!/bin/bash

pack(){
    p=$1
    shift
    cat $* > $p
}

if [ -e $1 ]
then
    echo "File already exists"
    exit 1
else

fi

pack uwu *#!/bin/bash

pack(){
    if [ -e $1 ]
    then
        return 1
    else
        p=$1
        shift
        cat $* > $p
        return 0
    fi
}

pack uwu *

if [ $? -ne 0 ]
then
    echo "File already exists"
    exit 1
else
    echo "Good!"
fi
adjwldjla
12345
