#!/bin/bash

#Output:

#        1
#       2 2
#      3 3 3
#     4 4 4 4
#    5 5 5 5 5
#   6 6 6 6 6 6
#  7 7 7 7 7 7 7
# 8 8 8 8 8 8 8 8
#9 9 9 9 9 9 9 9 9

for((i=1; i<=9; i++)); do
    for((j=1; j<=9 - i; j++)); do
        echo -n " "
    done
    for((j=1; j<=2*i - 1; j++)); do
        echo -n $i
    done
    echo ""
done